### ISSUE TITLE
老铁，“变量名：变量类型”和“-> None”是什么意思？

### ISSUE THREAD

**Issue by ShineforYG** [zhaobenx/Image-stitcher#3]
老铁，“变量名：变量类型”和“-> None”是什么意思？我用Pycharm没法编译呀！

**Comment by zhaobenx** [comment]
[**@ShineforYG**](https://github.com/ShineforYG) commented on [2018年5月30日 GMT+8 下午6:32](https://github.com/zhaobenx/Image-stitcher/issues/3#issue-327670939 "2018-05-30T10:32:36Z - Replied by Github Reply Comments"):
> 老铁，“变量名：变量类型”和“-> None”是什么意思？我用Pycharm没法编译呀！

这个是 Python 3.6的类型推定，3.5之前怕是只能删掉这些了
