### ISSUE TITLE
self._keypoints1:List[cv2.KeyPoint]  = None

### ISSUE THREAD

**Issue by zhouzhubin** [zhaobenx/Image-stitcher#4]
@zhaobenx 你好，这句话报语法错误，我是python3.5的，应该怎么修改？

**Comment by zhaobenx** [comment]
你好，这是python3.6的 type annotation，3.5的话要把冒号去掉
self._keypoints1 = None 
变成这样

**Comment by zhouzhubin** [comment]
@zhaobenx 谢谢了，代码可以运行了
