### ISSUE TITLE
Genetic Algorithm

### ISSUE THREAD

**Issue by toutuo** [zhaobenx/Image-stitcher#5]
您好，我没有搜到您说的那个关于遗传算法的论文？？

**Comment by toutuo** [comment]
我能看一下关于TMGA的那篇论文吗？这是我邮箱toutuo730@163.com，能麻烦您给我一下吗？感谢

**Comment by zhaobenx** [comment]
[image stitching.pdf](https://github.com/zhaobenx/Image-stitcher/files/3035850/image.stitching.pdf)
这是英文的，还有很罗嗦的中文版如果想看也可以发你

**Comment by toutuo** [comment]
真的很感谢
我看了一下英文版的，感觉还是挺简洁，您能抽时间再给我发一下中文版的吗
还有我想问一下，您这是本科毕设还是研究生毕设？

叨扰之处，再次抱歉

At 2019-04-03 04:38:41, "Ben" <notifications@github.com> wrote:


image stitching.pdf
这是英文的，还有很罗嗦的中文版如果想看也可以发你

**Comment by zhaobenx** [comment]
[中文版论文.pdf](https://github.com/zhaobenx/Image-stitcher/files/3036599/_.for.pdf)
这是本科毕设，比较简单其实
