### ISSUE TITLE
老铁您好，请问里面adjustM的作用是什么？

### ISSUE THREAD

**Issue by reacher-l** [zhaobenx/Image-stitcher#7]

**Comment by zhaobenx** [comment]
就是代码是把a图拼到b图上，通过adjustM计算出拼接后图像的大小和位置，水平移动，让全部像素都出现在画面里。

**Comment by reacher-l** [comment]
谢谢老铁


------------------ 原始邮件 ------------------
发件人: "Ben"<notifications@github.com>;
发送时间: 2019年8月9日(星期五) 下午4:12
收件人: "zhaobenx/Image-stitcher"<Image-stitcher@noreply.github.com>;
抄送: "In diesem Lied"<2698913156@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [zhaobenx/Image-stitcher] 老铁您好，请问里面adjustM的作用是什么？ (#7)




就是代码是把a图拼到b图上，通过adjustM计算出拼接后图像的大小和位置，水平移动，让全部像素都出现在画面里。
