### ISSUE TITLE
楼主，这个可以拼接地图吗？

### ISSUE THREAD

**Issue by NewRudy** [zhaobenx/Image-stitcher#8]
楼主你好，这个可以拼接地图吗

**Comment by zhaobenx** [comment]
其实这个只是应用于学习，真正的拼接其实效率并不高，建议你可以用一些其他现成的软件，比如ps，ptgui或者微软的ice 这是个免费软件

**Comment by NewRudy** [comment]
> 其实这个只是应用于学习，真正的拼接其实效率并不高，建议你可以用一些其他现成的软件，比如ps，ptgui或者微软的ice 这是个免费软件

嗯嗯，好的
